# /root/projects/atom_agents/interfaces/__init__.py
"""
Interface Module for the Synapse Platform.

This module defines the core data contracts (Pydantic models) that are used
for communication between different services and components of the system.
It acts as the single source of truth for data structures like PlanBlueprint,
AgentResult, ContextBuildConfig, etc.

This file is automatically generated from interfaces.md.
"""

# Import all models for easy access
from .interfaces import (
    # Plan Blueprint related
    PlanBlueprint,
    TaskDefinition,
    EdgeDefinition,
    TaskUpdate,
    DataFlow,
    ContextOverrides,
    
    # Agent Result related
    AgentResult,
    AgentIntent,
    FinalAnswer,
    ToolCallRequest,
    FailureDetails,
    
    # Tool Result related
    ToolResult,
    
    # Context related
    ContextBuildConfig,
    
    # Task Directives
    TaskDirectives,
    LoopDirective,
    Condition,
    
    # Human Intervention
    InterventionRequest,
)

__all__ = [
    # Plan Blueprint related
    "PlanBlueprint",
    "TaskDefinition",
    "EdgeDefinition",
    "TaskUpdate",
    "DataFlow",
    "ContextOverrides",
    
    # Agent Result related
    "AgentResult",
    "AgentIntent",
    "FinalAnswer",
    "ToolCallRequest",
    "FailureDetails",
    
    # Tool Result related
    "ToolResult",
    
    # Context related
    "ContextBuildConfig",
    
    # Task Directives
    "TaskDirectives",
    "LoopDirective",
    "Condition",
    
    # Human Intervention
    "InterventionRequest",
]
